---
name: gettsim-rtd
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - ipywidgets
  - jupyterlab

  # gettsim dependencies
  - astor
  - dags
  - ipywidgets
  - networkx
  - numpy
  - numpy_groupies
  - pandas
  - pip
  - plotly>=5.24,<6
  - pygments
  - pygraphviz
  - pytest
  - pyyaml

  # dependencies for building the documentation
  - myst-parser
  - nbsphinx
  - pydata-sphinx-theme
  - sphinx
  - sphinx-automodapi<0.17.0
  - sphinx-copybutton
  - pip:
      - -e ../
      - git+https://github.com/OpenSourceEconomics/dags
      - flatten_dict
