name: gettsim
channels:
  - conda-forge
dependencies:
  - bokeh
  - dags
  - ipywidgets
  # Jinja2 3.1.0 breaks docs. Keep until nbconvert or Jinja2 fixes it.
  - jinja2<3.1.0
  - jupyterlab
  - nbsphinx
  - networkx
  - numpy_groupies
  - numpydoc
  - pandas
  - pip
  - pydot
  - pygments
  - pytest
  - python
  - pyyaml
  - restructuredtext_lint
  # Automodapi leads to error within numpy_groupies/numba for sphinx 5.1.1
  # See: https://github.com/astropy/sphinx-automodapi/issues/148
  - sphinx=5.1.0
  - sphinx_rtd_theme
  - sphinx-automodapi
  - sphinx-copybutton
  - myst-parser
  - pip:
      - plotly
