---
name: gettsim-docs

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python
  - pip >=21.1
  - dags
  - ipywidgets
  # Jinja2 3.1 does not work with nbconvert
  # E.g., https://github.com/jupyter/nbconvert/issues/1740
  - jinja2<3.1
  - jupyterlab
  - networkx
  - numpy_groupies
  - numpydoc
  - pandas
  - pydot
  - pygments
  - pytest
  - pyyaml
  # Documentation

  # Automodapi leads to error within numpy_groupies/numba for sphinx 5.1.1
  # See: https://github.com/astropy/sphinx-automodapi/issues/148
  - sphinx=5.1.0
  - myst-parser
  - pydata-sphinx-theme>=0.3.0
  - sphinx-automodapi
  - sphinx-copybutton
  - nbsphinx
  - pip:
      - plotly
      - kaleido
      - -e ..
